# Generated by Django 4.1.4 on 2022-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Ожидает оплату', 'Ожидает оплату'), ('Оплачен', 'Оплачен'), ('Отменен', 'Отменен')], default='Ожидает оплату', max_length=50),
        ),
    ]
