# Generated by Django 4.1.4 on 2022-12-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
        ('assignments', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.counterparty'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
    ]
