# Generated by Django 4.1.4 on 2022-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('representative', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('type', models.CharField(choices=[('ООО', 'Общество с ограниченной отвественностью'), ('ИП', 'Индивидуальный предприниматель'), ('ОАО', 'Открытое акционерное общество'), ('ЗАО', 'Закрытое акционерное общество')], max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
